Repository TEAM-BeautiFlow/BeautiFlow_BE, pull requests merged in 2025-07, with the labels that each got.

#19 [FEAT] 매장 기본 정보 관리 기능 구현
  build.gradle
  src/main/java/com/beautiflow/chat/ChatRoom.java
  src/main/java/com/beautiflow/global/common/error/ShopErrorCode.java
  src/main/java/com/beautiflow/global/common/s3/S3Service.java
  src/main/java/com/beautiflow/global/common/s3/S3UploadResult.java
  src/main/java/com/beautiflow/reservation/converter/ShopConverter.java
  src/main/java/com/beautiflow/shop/controller/ShopManageController.java
  src/main/java/com/beautiflow/shop/domain/Shop.java
  src/main/java/com/beautiflow/shop/domain/ShopImage.java
  src/main/java/com/beautiflow/shop/dto/ShopInfoRes.java
  src/main/java/com/beautiflow/shop/dto/ShopUpdateReq.java
  src/main/java/com/beautiflow/shop/repository/ShopImageRepository.java
  src/main/java/com/beautiflow/shop/repository/ShopManageRepository.java
  src/main/java/com/beautiflow/shop/service/ShopManageService.java
  src/main/java/com/beautiflow/user/domain/User.java
Labels: ✨ Feature

#33 [REFACTOR] shop 관련 코드 위치 수정
  src/main/java/com/beautiflow/reservation/repository/ShopRepository.java
  src/main/java/com/beautiflow/shop/controller/ShopController.java
  src/main/java/com/beautiflow/shop/controller/ShopManageController.java
  src/main/java/com/beautiflow/shop/converter/ShopConverter.java
  src/main/java/com/beautiflow/shop/dto/ShopDetailResponse.java
  src/main/java/com/beautiflow/shop/repository/ShopRepository.java
  src/main/java/com/beautiflow/shop/service/ShopManageService.java
  src/main/java/com/beautiflow/shop/service/ShopService.java
Labels: 🛠️ Refactor

#43 [FEAT} 시술 및 옵션 조회
  src/main/java/com/beautiflow/shop/controller/ShopController.java
  src/main/java/com/beautiflow/shop/converter/ShopConverter.java
  src/main/java/com/beautiflow/shop/dto/ShopDetailRes.java
  src/main/java/com/beautiflow/shop/service/ShopService.java
Labels: ✨ Feature

#48 [REFACT] 스웨거 공통 추가 설정 by 로그인
  src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
  src/main/java/com/beautiflow/global/common/config/SwaggerConfig.java
  src/main/java/com/beautiflow/global/common/security/CustomOAuth2User.java
Labels: 🛠️ Refactor

#40 [FEAT] 매장 공지사항 crud 구현
  src/main/java/com/beautiflow/global/common/error/ShopErrorCode.java
  src/main/java/com/beautiflow/shop/controller/ShopNoticeController.java
  src/main/java/com/beautiflow/shop/domain/ShopNotice.java
  src/main/java/com/beautiflow/shop/dto/NoticeCreateReq.java
  src/main/java/com/beautiflow/shop/dto/NoticeUpdateReq.java
  src/main/java/com/beautiflow/shop/dto/ShopNoticeRes.java
  src/main/java/com/beautiflow/shop/repository/ShopNoticeRepository.java
  src/main/java/com/beautiflow/shop/service/ShopNoticeService.java
Labels: ✨ Feature

#57 workflow 수정
  .github/workflows/deploy.yml
  src/main/java/com/beautiflow/shop/controller/ShopController.java
Labels: 👾 Bug

#56 [FEAT] JWT관련 예외 처리, 액세스 토큰 재발급 구현
  build.gradle
  src/main/java/com/beautiflow/global/common/config/RedisConfig.java
  src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
  src/main/java/com/beautiflow/global/common/error/CommonErrorCode.java
  src/main/java/com/beautiflow/global/common/error/UserErrorCode.java
  src/main/java/com/beautiflow/global/common/handler/ExceptionAdvice.java
  src/main/java/com/beautiflow/global/common/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/beautiflow/global/common/security/JWTFilter.java
  src/main/java/com/beautiflow/global/common/security/annotation/AuthCheckAspect.java
  src/main/java/com/beautiflow/global/common/security/authentication/CustomOAuth2User.java
  src/main/java/com/beautiflow/global/common/security/authentication/CustomOAuth2UserService.java
  src/main/java/com/beautiflow/global/common/security/authentication/CustomSuccessHandler.java
  src/main/java/com/beautiflow/global/common/security/dto/JWTErrorRes.java
  src/main/java/com/beautiflow/global/common/security/filter/JWTExceptionFilter.java
  src/main/java/com/beautiflow/global/common/security/filter/JWTFilter.java
  src/main/java/com/beautiflow/global/common/util/JWTUtil.java
  src/main/java/com/beautiflow/global/common/util/RedisTokenUtil.java
  src/main/java/com/beautiflow/shop/controller/CalendarCheckController.java
  src/main/java/com/beautiflow/shop/controller/ShopController.java
  src/main/java/com/beautiflow/user/controller/UserController.java
  src/main/java/com/beautiflow/user/dto/TokenReq.java
  src/main/java/com/beautiflow/user/dto/TokenRes.java
  src/main/java/com/beautiflow/user/service/RefreshService.java
Labels: ✨ Feature

#75 upload artifact 버전 오류 수정
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#71 [FEAT] application-prod 추가
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🌎 Deploy

#79 test yml aws 설정 추가
  src/main/resources/application-test.yml
Labels: 🌎 Deploy

#80 deploy 환경변수 주입
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#81 artifact 보고서 추가
  .github/workflows/deploy.yml
Labels: 🌎 Deploy
